name: perso
description: Personalized training plans

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  # Dart
  collection: ^1.17.2

  # BLoC
  flutter_bloc: ^8.1.3

  # Dependency injection (DI)
  get_it: ^7.6.4
  injectable: ^2.3.2

  # Navigation
  go_router: ^11.1.4

  # Location
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  geocoding: ^2.1.1

  # Firebase
  firebase_auth: ^4.6.3
  flutter_rating_bar: ^4.0.1
  firebase_core: ^2.14.0
  firebase_storage: ^11.2.6
  cloud_firestore: ^4.9.3

  # Widgets
  country_picker: ^2.0.20
  flutter_svg: ^2.0.5
  flutter_form_builder: ^9.0.0
  cupertino_icons: ^1.0.6
  sticky_headers: ^0.3.0
  video_player: ^2.8.1
  table_calendar: ^3.0.9
  stream_chat_flutter: ^7.0.0

  #Http connection with API
  http: ^1.1.2

  # Utils
  uuid: ^3.0.7
  shared_preferences: ^2.2.0
  image_picker: ^1.0.4

  # Code generation
  freezed_annotation: ^2.2.0
  spider: ^4.2.2

dependency_overrides:
  photo_manager: ^3.0.0-dev.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  injectable_generator: ^2.1.3
  freezed: ^2.3.2
  flutter_lints: ^2.0.0
  very_good_analysis: ^5.1.0
  #translations_cleaner: ^0.0.5
  #delete_un_used_assets: ^1.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

  assets:
    - assets/images/
    - assets/vectors/
    - assets/videos/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages