name: Perso
description: Personalized training plans
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  intl:
  flutter_bloc: ^8.1.2
  injectable: ^2.1.0
  get_it: ^7.2.0
  injectable_generator: ^2.1.3
  flutter_platform_widgets: ^3.0.0
  go_router: ^6.0.7
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  flutter_svg: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:
  generate: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
  assets:
    - assets/images/
  uses-material-design: true