name: perso
description: Personalized training plans

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # Dart
  collection: ^1.18.0

  # BLoC
  flutter_bloc: ^8.1.6

  # Dependency injection (DI)
  get_it: ^7.7.0
  injectable: ^2.4.4

  # Navigation
  go_router: ^14.2.3

  # Location
  google_maps_flutter: ^2.9.0
  location: ^7.0.0
  geocoding: ^3.0.0

  # Firebase
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_storage: ^12.1.3
  cloud_firestore: ^5.2.1

  # Widgets
  flutter_rating_bar: ^4.0.1
  country_picker: ^2.0.26
  flutter_svg: ^2.0.10+1
  flutter_form_builder: ^9.4.1
  cupertino_icons: ^1.0.8
  sticky_headers: ^0.3.0+2
  video_player: ^2.9.1
  table_calendar: ^3.1.2
  stream_chat_flutter: ^8.0.0

  #Http connection with API
  http: ^1.2.2

  # Utils
  uuid: ^4.4.2
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  connectivity_plus: ^6.0.5

  # Code generation
  freezed_annotation: ^2.4.4
  spider: ^4.2.2
  flutter_launcher_icons: ^0.13.1
  json_annotation: ^4.9.0
  bloc_concurrency: ^0.2.5
  algoliasearch: ^1.22.1

dependency_overrides:
  photo_manager: ^3.2.3

dev_dependencies:
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.2
  flutter_lints: ^4.0.0
  very_good_analysis: ^6.0.0
  #translations_cleaner: ^0.0.5
  #delete_un_used_assets: ^1.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon_black.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

  assets:
    - assets/images/
    - assets/vectors/
    - assets/videos/
    - assets/icon/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages