name: Perso
description: Personalized training plans
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=2.18.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  intl:
  flutter_bloc: ^8.1.2
  injectable: ^2.1.0
  get_it: ^7.2.0
  injectable_generator: ^2.1.3
  flutter_platform_widgets: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
flutter:
  uses-material-design: true